# Generated by Django 5.1.3 on 2025-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('sci-fi', 'Sci-Fi'), ('romance', 'Romance'), ('mystery', 'Mystery'), ('biography', 'Biography'), ('history', 'History'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('horror', 'Horror')], max_length=50),
        ),
    ]
