# Generated by Django 5.1.3 on 2025-04-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('sci-fi', 'Sci-Fi'), ('romance', 'Romance'), ('mystery', 'Mystery'), ('history', 'History'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('crime', 'Crime'), ('actiom', 'Action'), ('humor', 'Humor'), ('adventure', 'Adventure'), ('autobiography', 'Autobiography'), ('cookbook', 'Cookbook'), ('philosophy', 'Philosophy'), ('other', 'Other')], max_length=50),
        ),
    ]
