# Generated by Django 5.1.3 on 2025-04-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=111),
            preserve_default=False,
        ),
    ]
