# Generated by Django 5.1.3 on 2025-04-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='famous_quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
