# Generated by Django 5.1.3 on 2025-05-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_book_facts_review_likes_bookrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.DeleteModel(
            name='BookRating',
        ),
    ]
