# Generated by Django 5.1.3 on 2025-05-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_bookrating_reviewlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.book'),
        ),
    ]
