# Generated by Django 5.1.3 on 2025-05-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_userprofile_bio_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
