# Generated by Django 5.1.3 on 2025-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_readinglog_unique_together_currentlyreading'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readinglog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='readinglog',
            name='book',
        ),
        migrations.RemoveField(
            model_name='readinglog',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='curently_reading_books',
            field=models.ManyToManyField(blank=True, related_name='currently_reading_by', to='app.book'),
        ),
        migrations.DeleteModel(
            name='CurrentlyReading',
        ),
        migrations.DeleteModel(
            name='ReadingLog',
        ),
    ]
