# Generated by Django 5.1.3 on 2025-07-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_readinglog_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='curently_reading_books',
            new_name='currently_reading_books',
        ),
    ]
