# Generated by Django 5.1.3 on 2025-07-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_readingprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readingprogress',
            unique_together=set(),
        ),
    ]
