# Generated by Django 5.1.3 on 2025-07-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_readingprogress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pics/'),
        ),
    ]
