# Generated by Django 5.1.3 on 2025-07-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_book_published_date_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
