# Generated by Django 5.1.3 on 2025-08-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_favorite_books_userprofile_wishlist_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('born', models.DateField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('alma_mater', models.TextField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('notable_works', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
