# Generated by Django 5.1.3 on 2025-08-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='alma_mater',
        ),
    ]
