# Generated by Django 5.1.3 on 2025-08-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_author_alma_mater'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
