# Generated by Django 5.1.3 on 2025-08-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_author_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_summary',
        ),
    ]
