# Generated by Django 5.1.3 on 2025-08-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('sci-fi', 'Sci-Fi'), ('romance', 'Romance'), ('mystery', 'Mystery'), ('history', 'History'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('religion', 'Religion'), ('crime', 'Crime'), ('young adult', 'Young Adult'), ('humor', 'Humor'), ('adventure', 'Adventure'), ('autobiography', 'Autobiography'), ('science', 'Science'), ('psychology', 'Psychology'), ('other', 'Other')], max_length=50),
        ),
    ]
